name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
    - master
    paths:
    - '**.cs'
    - '**.csproj'
    - '*/package.json'
    - '*/packages.config'
    - '/.github/workflows/**'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        
      - name: Restore packages
        run: nuget restore log4net.unity.sln

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build
        run: msbuild log4net.unity.sln /t:Clean,Build -p:Configuration=Release
        
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:          
          format: 'YYYY-MM-DD-HH-mm-ss Z'
          
      - name: Commit & Push changes
        uses: actions-js/push@master        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Autobuild commit ${{ steps.time.outputs.time }}'
